import java.util.*;
class Book{
    private String author;
    private int price;
    private String title;
    static List<Book> books = new ArrayList<>();

    Book(){
        //Default Constructor
    }
    Book(String author, int price, String title){
        this.author = author;
        this.price = price;
        this.title = title;
    }

    public static List<Book> searchBookByAuthorName(List<Book> books, String author){
        List<Book> res = new ArrayList<>();
        for(Book book : books){
            if(book.author.equals(author)){
                res.add(book);
            }
        }
        return res;
    }

    public static void add(Book book){
        books.add(book);
    }

    public String toString(){
        return "Book: " + this.title + " is written by " + this.author + " & is priced at "+ this.price;
    }

    /* 
    Printing the list of Books/Calculating the total revenue generated by selling books should not be the responsibility of the Book class, rather there should be other utility classes defined for this

    public void print(List<Book> books){
        // Some Implementation
    }
    */


    
}